import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

const Home = () => {
  // testdata
  const data = [{
    name: 'Spaghetti bolognese',
    image: 'vercel.svg',
    ingredients: ['onion', 'salt', 'pepper']
  }];

  const sortOptions = ['az', 'za', 'time'];
  const [inputSearch, setInputSearch] = useState('');

  // When the user types in the searchbar
  const handleInputSearch = e => {
    const value = e.currentTarget.value;
    setInputSearch(value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ITP web case Kaj De Muynck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Title */}
        <h1 className={styles.title}>
          <p className={styles.title__start}>What are you</p>
          <p className={styles.title__end}>eating today?</p>
        </h1>
        
        {/* Searchbar */}
        <input type="search" value={inputSearch} onChange={handleInputSearch} />

        {/* Recommended */}
        <section className={styles.section}>
          <h2 className={styles.subtitle}>Recommended</h2>
          <article className={styles.recommended__item}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            <div>
              <h3 className={styles.rotd__title}>Recipe of the day</h3>
              <p className={styles.rotd__name}>Spaghetti bolognese</p>
            </div>
          </article>
        </section>

        {/* Recipes */}
        <section className={styles.section}>
          <div className={styles.subtitle__wrapper}>
            <h2 className={styles.subtitle}>Recipes</h2>
            <div className={styles.section__options}>
              <button className={styles.btn__sort}>
                <Image src="/vercel.svg" alt="sort" width={32} height={32} />
              </button>
            </div>
          </div>
          <ul className={styles.recipes}>
            {data.map((recipe, index) => (
              <li className={styles.recipe} key={index}>
                <Image className={styles.recipe__img} src={`/${recipe.image}`} alt="recipe" width={80} height={80} />
                <p className={styles.recipe__name}>{recipe.name}</p>
                <p className={styles.recipe__ingredients}>{recipe.ingredients.join(', ')}</p>
              </li>
            ))}
          </ul>
        </section>
      </main>

      {/* Footer */}
      <footer className={styles.footer}>
        <p>&copy; Kaj De Muynck 2021</p>
      </footer>
    </div>
  )
}

export default Home;