import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';
import { request } from "../lib/datocms";
import ListOfRecipes from '../components/ListOfRecipes';
import Recommended from '../components/Recommended';

let randomRecipe = false;
const HOMEPAGE_QUERY = `query HomePage {
  allRecipes(orderBy: name_ASC) {
    id
    name
    slug
    time
    image {
      imageSmall: responsiveImage(imgixParams: {w: "80", h: "80", fit: crop}) {
        src
        srcSet
        webpSrcSet
        width
        title
        height
        base64
        alt
        aspectRatio
        sizes
      }
      imageBig: responsiveImage(imgixParams: {w: "480", h: "320", fit: crop}) {
        src
        srcSet
        webpSrcSet
        width
        title
        height
        base64
        alt
        aspectRatio
        sizes
      }
    }
  }
}`;

const INGREDIENTS_QUERY = `query GetIngredientsFromRecipe($id: ItemId) {
  allRecipeIngredients(filter: { recipe: { eq: $id } }) {
    ingredient {
      name
      plural
    }
  }
}`;

export const getStaticProps = async () => {
  const recipes = await request({
    query: HOMEPAGE_QUERY
  });

  const data = [...recipes.allRecipes];
  for (const recipe of recipes.allRecipes) {
    const ingredients = await request({
      query: INGREDIENTS_QUERY,
      variables: { id: recipe.id }
    });
    recipe.ingredients = ingredients.allRecipeIngredients.map(item => item.ingredient);
  }

  return {
    props: { data }
  };
}

const Home = ({ data }) => {
  const [inputSearch, setInputSearch] = useState('');
  if (!randomRecipe) randomRecipe = data[Math.floor(Math.random() * data.length)];

  // When the user types in the searchbar
  const handleInputSearch = e => {
    const value = e.currentTarget.value;
    setInputSearch(value);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>ITP web case Kaj De Muynck</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* Title */}
        <h1 className={styles.title}>
          <p className={styles.title__start}>What are you</p>
          <p className={styles.title__end}>eating today?</p>
        </h1>
        
        {/* Searchbar */}
        <input className={styles.searchbar} type="search" value={inputSearch} onChange={handleInputSearch} placeholder="Search" />

        {/* Recommended */}
        <Recommended recipe={randomRecipe} />

        {/* Recipes */}
        <ListOfRecipes data={data} inputSearch={inputSearch} />
      </main>

      {/* Footer */}
      <footer className={styles.footer}>
        <p>&copy; Kaj De Muynck 2021</p>
      </footer>
    </div>
  )
}

export default Home;